### ISSUE TITLE
Long press delete post prompt shows for any user's post.

### ISSUE THREAD

**Issue by isdavid** [Daviddt17/island-android-app#61]

**Comment by gopenshaw** [comment]
I can see the bug on Samsung Galaxy S4 (Android 5.0.1)
I can't recreate the bug on Verizon Ellipsis (Android 4.4.2)

**Comment by gopenshaw** [comment]
This issue only occurs when the feed changes dynamically, ie from a refresh action. If app is restarted, and feed is re-loaded, everything will appear correct.

The problem is that the listeners get bound to the post holders, and when the feed changes, the post that is in a particular holder may change, but the original listener is still there.

**Comment by isdavid** [comment]
Closed with #88
